// IE Web Notifications
// Copyright (C) 2015-2016, Sergei Zabolotskikh. All rights reserved.
//
// This file is a part of IE Web Notifications project.
// The use and distribution terms for this software are covered by the
// BSD 3-Clause License (https://opensource.org/licenses/BSD-3-Clause)
// which can be found in the file LICENSE at the root of this distribution.
// By using this software in any fashion, you are agreeing to be bound by
// the terms of this license. You must not remove this notice, or
// any other, from this software.

#include "../COMInterfaces.idl";

cpp_quote("#ifdef __cplusplus")
cpp_quote("namespace ukot { namespace ie_web_notifications { namespace com {")
cpp_quote("#endif")

[
  uuid(B711FAD4-1850-4221-BB31-8791CA9FAB01),
  version(1.0),
]
library ie_web_notificationsd2dLib
{
  importlib("stdole2.tlb");
  [
    uuid(B711FAD4-1850-4221-BB31-8791CA9FAB02)
  ]
  coclass D2DNotificationWindowFactory
  {
    [default] interface INotificationWindowFactory;
  };
};

cpp_quote("#ifdef __cplusplus")
cpp_quote("class DECLSPEC_UUID(\"B711FAD4-1850-4221-BB31-8791CA9FAB01\") ie_web_notificationsd2dLib;")
cpp_quote("#endif")


cpp_quote("#ifdef __cplusplus")
cpp_quote("}}}")
cpp_quote("#endif")
